trigger:
  branches:
    include:
      - main  # Trigger pipeline only for commits to the main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Check out the code
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Use the required Python version
    addToPath: true

# Step 2: Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install pytest pytest-html fastapi uvicorn httpx
  displayName: 'Install dependencies'

# Step 3: Run pytest
- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)  # Ensure directory exists
    pytest --html=$(Build.ArtifactStagingDirectory)/report.html --self-contained-html
  displayName: 'Run Tests and Generate Report'

# Step 4: Fail pipeline on test failure
- script: |
    if grep -q "FAILURES" report.html; then
      echo "Tests failed. Commit will not be pushed to master."
      exit 1
    fi
  displayName: 'Check for test failures'

# Step 4: Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/report.html'  # Path to your test report
    failTaskOnFailedTests: true
    testRunTitle: 'Test Results'
  displayName: 'Publish Test Results'

# Step 5: Send test report
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'pytest-report'
    targetPath: '$(Build.ArtifactStagingDirectory)'  # Match report storage location
  displayName: 'Publish Pytest Report'

# #Step 6: Send Email
# - task: SendEmailTask@1
#   inputs:
#     to: 'sweeda@anoralabs.com'
#     subject: 'Pytest Report for Main Branch'
#     body: 'Find the pytest report attached.'
#     attachment: '$(System.DefaultWorkingDirectory)/report.html'
